- nextflow.config
- subworkflows/local/assemble/main.nf
- workflows/genomeassembler.nf
After switching to the updated hifiasm module in the assembly subworkflow, I added functionality to use `--ont` with hifiasm. This contained a mistake.
> fix assemble subworkflow

- assets/report/report.qmd
- conf/modules.config
- docs/output.md
- subworkflows/local/assemble/main.nf
- subworkflows/local/prepare_shortreads/main.nf
- subworkflows/local/scaffolding/links/main.nf
- subworkflows/local/scaffolding/longstitch/main.nf
With the switch to the nf-core module I also need to update the configuration of that module.
> module configuration

- modules/local/jellyfish/main.nf
> fix jellyfish singularity path

- nextflow_schema.json
This (hopefully) solves #73 assuming that the documentation was insufficient to use this feature.
> update schema on assembly skiping

- .github/workflows/download_pipeline.yml
- conf/test.config
- modules/local/collect_reads/main.nf
- modules/local/genomescope/main.nf
- modules/local/gfa2fa/main.nf
- modules/local/jellyfish/main.nf
- modules/local/links/main.nf
- modules/local/longstitch/main.nf
- modules/local/medaka/main.nf
- modules/local/medaka/medaka_consensus/environment.yml
- modules/local/medaka/medaka_consensus/main.nf
- modules/local/nanoq/main.nf
- modules/local/quast/main.nf
- modules/local/ragtag/main.nf
- modules/local/report/main.nf
There is an issue with the [`download` GHA](https://github.com/nf-core/genomeassembler/actions/runs/13259363850).
This continues to fail during automated testing, there is no obvious error message and I am a bit confused what is going on. For now I have added stubs for the local modules that are part of this test, to see if I can get a successful stub run. While doing this, I realised that there are no stubs for any of the local modules. I will add those in the near future. 
I also noticed that test.config contained a duplicated resourceLimits block, this has been removed.
> Add stubs for local modules

- .nf-core.yml
- ro-crate-metadata.json
> add rocrate

- assets/schema_input.json
> review: input_schema remove must from optional inputs

- README.md
> Review: add affiliation, proper github links

- configs/hifi_flye.config
- configs/hifi_hifiasm.config
- configs/hifi_ont_flye_on_hifiasm.config
- configs/hifi_ont_hifiasm_ul.config
- configs/ont_flye.config
- configs/ont_hifiasm.config
- docs/usage.md
> reviews: remove duplicate from usage; add short info to configs

- conf/modules.config
There was another issue in the config for liftoff modules
> missing slash in outdir for liftoff 

- .nf-core.yml
- nextflow.config
- nextflow_schema.json
This removes some multiqc leftovers from the template in nextflow.config and nextflow_schema.json
> remove multiqc settings

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release-announcements.yml
- .nf-core.yml
- .pre-commit-config.yaml
- assets/sendmail_template.txt
- docs/output.md
- docs/usage.md
- main.nf
- modules/nf-core/fastqc/tests/tags.yml
- nextflow.config
- ro-crate-metadata.json
- subworkflows/local/utils_nfcore_genomeassembler_pipeline/main.nf
- tower.yml
- workflows/genomeassembler.nf
This is a template sync to 3.2.0, which seems to not have synced properly before
> Template -> 3.2.0

- .github/workflows/ci.yml
- nextflow.config
This PR changes:
`ci.yml`: I have added back in the installation step(s) for singularity and conda
`nextflow.config`: When revisiting this file for singularity setup I noticed that a lot of the profiles contained duplicated blocks, I have removed those.
> Fix singularity CI, clean nextflow.config

- modules/nf-core/merqury/merqury/main.nf
- modules/nf-core/merqury/merqury/merqury-merqury.diff
Another attempt to make outputs optional to get through with the full_test data
> patch merqury for AWS test

- docs/usage.md
`ont_hifiasm` was missing from usage.md
> add missing profile

- .nf-core.yml
- CHANGELOG.md
- nextflow.config
- ro-crate-metadata.json
Preparing for the next patch release which will probably fix problems discovered after the release of 1.0.0
> version bump to 1.0.1dev

- .nf-core.yml
- CHANGELOG.md
- nextflow.config
- ro-crate-metadata.json
Version bumps for bugfix release 1.0.1.
> version 1.0.1

- .nf-core.yml
- CHANGELOG.md
- nextflow.config
- ro-crate-metadata.json
Bumping version of dev branch post release
> version bump 1.1.0dev

- modules/nf-core/fastqc/main.nf
During a template merge something happened to this module, and a bunch of lines were duplicated.
> remove duplicated lines from fastqc module

- CHANGELOG.md
- subworkflows/local/utils_nfcore_genomeassembler_pipeline/main.nf
Checking if assemblies should actually be done before throwing an error regarding assemblies. See #143
> check if assembly is skipped in initialization, closes #143

- CHANGELOG.md
- docs/usage.md
- modules/local/collect_reads/main.nf
`--collect` expects a folder, input validation expects a file, this is incompatible. `COLLECT_READS` should now work with many files from a glob.
> make collect reads accept files, closes #141

- docs/usage.md
Make more explicit in `usage.md` that paths should be absolute.
> Docs update

- CHANGELOG.md
- assets/report/report.qmd
- modules/local/report/environment.yml
- modules/local/report/main.nf
Update to reporting:
- Tabular outputs for quast and BUSCO via `gt`
- updated container and conda env to include `gt`
- updated `CHANGELOG.md`
> Report update

- modules/local/report/main.nf
singularity container had no prefix, see #152
> add prefix to singularity container for report
