nf-core/genomeassembler

.github/workflows/ci.yml
I noticed that GHA only runs with `docker`, I think it would make sense to also include `conda` and `singularity`.
=> GHA: include conda in tests

README.md
The metromap displayed in the readme now switches between light/dark version based on GH color scheme.
=> README: switch metromap based on theme

modules/local/report/main.nf
The report module used an oras container for singularity. Since I do not use singularity I was not aware that this does not work with older singuarlity versions. With this I switch to the https container.
=> use https container for singularity

.github/workflows/ci.yml, .github/workflows/download_pipeline.yml, conf/test.config
I noticed that the tests were missing the assembler that was tested, now the tests are named `NXF_VER | assembler | profile`, instead of `NXF_VER | | profile`.
The `download_pipeline` action did not specify which assembler to test, it now tests `hifiont_flyehifiasm`, which runs both flye and hifiasm.
=> GHA: update CI-tests

modules/local/collect_reads/environment.yml, modules/local/collect_reads/main.nf
The `collect_reads` module was using a python3.11 container, but it seems more reasonable to use the coreutils / grep / gzip container and environment that is also used by `gfa2fa`.
=> use different container for collect_reads

assets/report/report.qmd
There was extra indentation in the yaml header of the report qmd file, which caused an error during rendering. I assume I added this by accident when I changed indentation to please `.editorconfig`. I have also updated the link to link to the nf-core repo instead of my fork.
=> indentation in report yaml

modules/local/quast/main.nf
When updating quast, I forgot a `/` in the `results` output path.
=> quast output path

conf/modules.config, modules/local/quast/main.nf
There was a mistake in the output path for the map_to_assembly output for the ragtag module.
Other commits for quast belong into #87
=> Fix modules.conf: ragtag map assembly output path

conf/modules.config
I noticed a mistake in the patterns for liftoff; since it is included in the `RUN_TOOL` subworkflows, the pattern must not include the `:` before `TOOL`
=> update LIFTOFF patterns

subworkflows/local/assemble/main.nf, subworkflows/local/jellyfish/main.nf, subworkflows/local/mapping/map_to_assembly/main.nf
This removes unused outputs (`*_bam_bai`) from `MAP_TO_ASSEMBLY` and updates `ASSEMBLE` to remove the channel that contained those outputs and did nothing with them.
I also added indentation in two if blocks in the jellyfish workflow.
=> remove ch_assembly_bam_bai, less outputs from map_to_assembly, indentation in jellyfish workflow

modules/local/ragtag/main.nf
The stub for ragtag was missing `touch`
=> add touch to ragtag stub

modules.json, modules/nf-core/merqury/merqury/main.nf, modules/nf-core/merqury/merqury/merqury-merqury.diff
The AWS test fails because merqury does not create the `_only.bed` file. 
I think this might be because of how the test-dataset was generated: it only contains reads that map to the region that is assembled, and I guess this could mean that there are no exclusive kmers?
=> optional merqury outputs for awstest

conf/modules.config
While exploring why test AWS tests fail, I noticed a weird filename, which i tracked back to using `meta_id` instead of `meta.id` in the closure that provides the `prefix` for this process.
=> replace meta_id with meta.id in ASSEMBLE:RAGTAG_SCAFFOLD

modules/nf-core/merqury/merqury/main.nf, modules/nf-core/merqury/merqury/merqury-merqury.diff
This is another attempt at getting merqury to work with the test dataset.
We have updated the short-read test data in https://github.com/nschan/test-datasets/tree/genomeassembler to have more differences between shortread and assembled sequences. Still, this dataset remains artificial and only produces a single contig/sequence during assembly, which means that some of the merqury files are not created.
=> patch merqury for AWS test

conf/test_full.config
This is an attempt to fix the failing AWS megatest. It fails because BUSCO emits the lineage-dir into `QC/BUSCO` and it seems that this causes problems with overwriting in the outdir when there are subfolders emitted that are not empty (at least that is my understanding of the error message). For this test only, the busco steps now emit into a subworkflow specific subdir (`QC/BUSCO/<stage>`). This error is specific for runs where the lineage files are downloaded by the pipeline, and probably S3. I think users should pre-fetch the busco lineage for production runs, otherwise each BUSCO process will download the lineage files again.
=> AWS-test: busco output dirs

conf/modules.config, conf/test_full.config
Publishing `busco_downloads/` creates a problem during AWS tests. 
The glob `*{-busco,_summary}*` specified in the `publishDir` `pattern` should catch all other files created by BUSCO:
```
tuple val(meta), path("*-busco.batch_summary.txt")                , emit: batch_summary
tuple val(meta), path("short_summary.*.txt")                      , emit: short_summaries_txt   , optional: true
tuple val(meta), path("short_summary.*.json")                     , emit: short_summaries_json  , optional: true
tuple val(meta), path("*-busco/*/run_*/full_table.tsv")           , emit: full_table            , optional: true
tuple val(meta), path("*-busco/*/run_*/missing_busco_list.tsv")   , emit: missing_busco_list    , optional: true
tuple val(meta), path("*-busco/*/run_*/single_copy_proteins.faa") , …
```
=> Disable publishing of BUSCO downloads

CHANGELOG.md, docs/usage.md
Now that the AWS megatest passed (https://cloud.seqera.io/orgs/nf-core/workspaces/AWSmegatests/watch/10kkZuISqYOIH6) this is hopefully the final PR before merging dev into master and creating the first release.
The PR contains final changes for the release.
- Codename and Date (planned for tomorrow; 07.03.2025) added to `changelog.md` 
- [03.07.2025] Fixed a mistake in `usage.md` where the shortread columns were named as `shortreads_[F,R]` instead of `shortread_[F,R]`
If I forgot anything please let me know :)
=> Codename and Date for first release

CHANGELOG.md, conf/modules.config, modules/local/longstitch/main.nf, subworkflows/local/assemble/main.nf, subworkflows/local/ont/main.nf, subworkflows/local/scaffolding/longstitch/main.nf, subworkflows/local/scaffolding/main.nf, subworkflows/local/utils_nfcore_genomeassembler_pipeline/main.nf, workflows/genomeassembler.nf
The `longstitch` module contained a hardcoded genome-size value, an oversight that should not have made it into the release. 
While fixing this, I realized that the way `genome_size` was handled with `flye` was also bad, since it relied on changing `params.genome_size`, if there was an estimated sample-specific value from genomescope; I am not even sure that worked correctly. Generally, now the `genome_size` channel is used and either contains the value of `params.genome-size`, which can be updated with the estimated genome-size from `genomescope` in the `ONT` module.
For flye, passing genome_size is now handled by _temporarily_ storing genome_size as part of the `meta`-map, from where can be used with `ext.args` via `modules.conf`, to avoid having to patch the `flye` module. Of course, …
=> use correct genome-size for flye and longstitch

CHANGELOG.md, modules/local/jellyfish/dump/main.nf, modules/local/jellyfish/histo/main.nf, modules/local/jellyfish/stats/main.nf
as reported in #118 there is still a wrong singularity url for some of the jellyfish processes. These are corrected here.
=> Jellyfish singularity container

modules/local/medaka/main.nf
It was reported in #139 that the url for the medaka singularity container is wrong, this should be correct.
=> fix medaka singularity container url, closes #139

subworkflows/local/assemble/main.nf
This fixes an oversight where the mapping to reference was skipped with `hifiasm_on_hifiasm`, because the reads were not specified for this strategy.
=> enable mapping to ref for hifiasm_on_hifiasm

conf/modules.config
GFA_2_FA_ONT and GFA_2_FA emitted into the same directory, which they should not. This is part of adding `hifiasm_on_hifiasm`, see #146.
=> fix GFA_2_FA* outputs
